config/routes.rb
Rails.application.routes.draw do

  
  scope module: 'authors' do
    resources :posts do
      resources :elements
      

      # member routes act on single object but collection does not
      member do
        get :publish # member routes generate URL like /posts/:post_id/publish
        get :unpublish # member routes generate URL like /posts/:post_id/unpublish
      end
      
      # collection do
      #   get :publish # member routes generate URL like /posts/publish
      #   get :unpublish # member routes generate URL like /posts/unpublish
      # end

    end
  end	
  
  devise_for :authors
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post
  validates :element_type, inclusion: {in: ['paragraph', 'image', 'video-embed']}

  has_rich_text :content
  has_one_attached :image

  def paragraph?
    self.element_type == 'paragraph'
  end

  def image?
    self.element_type == 'image'
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :elements

  has_one_attached :header_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors/elements_controller.rb
# it can be done with modules as well for namespacing like its done in posts controller

class Authors::ElementsController < AuthorsController
  
  before_action :set_post
  before_action :set_element, only: [:show, :edit, :update, :destroy]

  # GET /elements
  def index
    @elements = Element.all
  end

  # GET /elements/1
  def show
  end

  # GET /elements/new
  def new
    @element = Element.new
  end

  # GET /elements/1/edit
  def edit
  end

  # POST /elements
  def create
    @element = @post.elements.build(element_params)

    _notice = nil
    if @element.save
      _notice = 'Element was successfully created.'
    else
      _notice = @element.errors.full_messages.join(" .")
    end

    redirect_to edit_post_path(@post), notice: _notice
  end

  # PATCH/PUT /elements/1
  def update
    if @element.update(element_params)
      redirect_to edit_post_path(@post), notice: 'Element was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /elements/1
  def destroy
    @element.destroy
    redirect_to edit_post_path(@post), notice: 'Element was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    def set_post
      @post = current_author.posts.find(params[:post_id])
    end

    # Only allow a trusted parameter "white list" through.
    def element_params
      params.require(:element).permit(:element_type, :content, :post_id, :position, :image)
    end
end

app/controllers/authors/posts_controller.rb
module Authors  
  class PostsController < AuthorsController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /posts
    def index
      @posts = Post.all
    end

    # GET /posts/1
    def show
    end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit
      @paragraph = @post.elements.build(element_type: 'paragraph')
      @image = @post.elements.build(element_type: 'image')
    end

    # POST /posts
    def create
      @post = Post.new(post_params)

      if @post.save
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
    end

    def publish
      @post = Post.find(params[:post_id])
      @post.update(published_at: Time.now())

      redirect_to edit_post_path(@post), notice: 'Post was successfully pusblished.'
    end

    def unpublish
      @post = Post.find(params[:post_id])
      @post.update(published_at: nil)

      redirect_to edit_post_path(@post), notice: 'Post was successfully UnPusblished.'
    end

    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(:title, :description, :published, :publisshed_at, :author_id, :header_image)
      end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	before_action :authenticate_author!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/authors/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :header_image %>
    <%= form.file_field :header_image , class: "form-control"%>

    <%if post.header_image.present?%>
      <small> Current Image </small>
      <%= image_tag post.header_image, width:"100%"%>
    <%end%>
  </div>



  <!-- <div class="form-group">
    <%= form.label :published %>
    <%= form.check_box :published , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :publisshed_at %>
    <%= form.datetime_select :publisshed_at , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :author_id %>
    <%= form.text_field :author_id , class: "form-control"%>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<%= link_to 'Back', posts_path, class: "btn btn-secondary" %>
<div class="row">

 <div class="col-md-1">
 </div>
  
  <div class="col-md-3">
    <div class="card">
      <div class="card-header">
      <h6 class="card-title"> Editing Posts </h6>
      </div>
      <div class="card-body">
        
        <%= render 'form', post: @post %>
      </div>
      <div class="card-footer">
        <% if @post.published_at.present? %>
          <%= link_to 'UnPublish', unpublish_post_path(post_id: @post), class: "btn btn-secondary btn-dark btn-block"%>
        <%else%>
        <%= link_to 'Publish', publish_post_path(post_id: @post), class: "btn btn-secondary btn-block"%>
        <%end%>
      </div>
    </div>  
  </div>

  <div class="col-md-8">
    <!-- it Create path as well on the basis of [@post, @element] i.e posts/1/element -->
    <div class="mb-3">
    <!-- @paragraph is element object and same with image -->
      <%= form_with(model: [@post, @paragraph], html: {class: 'float-left mr-3'}) do |form|%>
        <%= form.hidden_field :element_type, value: 'paragraph'%>
        <%= form.button(type: "submit", class: 'btn btn-dark') do %>
          <i class="fas fa-paragraph"/></i>
        <%end%>
      <%end%>

      <%= form_with(model: [@post, @image]) do |form|%>
        <%= form.hidden_field :element_type, value: 'image'%>
        <%= form.button(type: "submit", class: 'btn btn-dark') do %>
          <i class="fas fa-image"/></i>
        <%end%>
      <%end%>
    </div>
    

    
      
      <div class="card mb-4">
        <div class="card-header text-right">
          <%if @post.published_at.present?%>
            <b>Published </b> <%= time_ago_in_words(@post.published_at)%> ago
          <%else%>
            <b>UnPublished</b>
          <%end%>
        </div>
        <div class='card-body pt-5'>
          
          <% @post.elements.each do |element|%>  
            <% if element.persisted?%>
              <div class="mb-3">
                <%if element.paragraph?%>
              
                  <%= form_with(model: [@post, element]) do |form|%>
                    <%= form.rich_text_area :content, value: 'paragraph'%>
                    <%= form.hidden_field :element_type, value: 'paragraph do'%>
                    <div class="mt-3 d-flex justify-content-between">
                        <div>
                          <%= form.submit 'Save', class: 'btn btn-primary mt-3' %>
                        </div>
                        <%= link_to "Delete", post_element_path(@post,element), method: :delete, class: 'btn btn-danger'%>
                      </div>
                    
                  <%end%>
                <%elsif element.image?%>

                  <% if element.image.present?%>
                    <%= image_tag element.image%>
                  <%else%>
                    <%= form_with(model: [@post, element]) do |form|%>
                      <%= form.file_field :image, value: 'paragraph'%>
                      <%= form.hidden_field :element_type, value: 'image'%>
                      <div class="mt-3 d-flex justify-content-between">
                        <div>
                          <%= form.submit 'Save', class: 'btn btn-primary mt-3' %>
                        </div>
                        <%= link_to "Delete", post_element_path(@post,element), method: :delete, class: 'btn btn-danger'%>
                      </div>
                      
                    <%end%>
                    
                  <%end%>
                  
                <%end%>

                
              </div>
            <%end%>
          <%end%>
        </div>
      </div>
        
  </div>
</div>

app/views/authors/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h4 class='d-flex justify-content-between mb-4'>
  <span>Posts</span>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary'%>
</h4>


<% @posts.each do |post| %>
  <%= link_to edit_post_path(post) do %>
     <div class="card mb-3">
      <div class="card-body">
        <div class="row">
           <div class="col-md-3">
            <%if post.header_image.present?%>
              <%= image_tag(post.header_image,  width: '60%')%>
            <%end%>
            
           </div>
           <div class="col-md-9">
            <h5 class="card-title mb-1 text-dark"> <%= post.title%></h5>
            <p class="text-secondary mb-0"> <%= post.description%></p>
           </div>
        </div>
        
      </div>
     </div>
   <%end%>
<%end%>

app/views/authors/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/authors/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @post.published %>
</p>

<p>
  <strong>Publisshed at:</strong>
  <%= @post.publisshed_at %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/home/index.html.erb
<%name = current_author.present? ? current_author.email : 'Stranger'%>
<h1> Welcome <%= name%></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectRails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel = "stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/18417089b4.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectRails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel = "stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/18417089b4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render "shared/navbar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Auth App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if author_signed_in?%>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_author_session_path, method: :delete, class: 'nav-link'%>
        </li>
      <%else%>
         <li class="nav-item">
          <%= link_to 'Register' , new_author_registration_path, class: 'nav-link'%>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign In', new_author_session_path, class: 'nav-link'%>
        </li>
      <%end%>
      
    </ul>
  </div>
</nav>